import "./globals.css";
import type { Metadata }          from "next";
import { Kanit }                  from "next/font/google";

import Navbar                     from '@/app/components/navbar/navbar'



//จัดการและโหลดฟอนต์ (Fonts)
const kanit = Kanit({
  subsets: ["thai", "latin"], // สำคัญ: ใส่ thai เพื่อให้สระไม่ลอย
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // เลือกน้ำหนักที่ต้องการ
  variable: "--font-kanit",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// ----------------------------------------------------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={`${kanit.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
